### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by Kodedyukh** [remy/jsconsole#100]
After installing jsconsole on my local machine (Ubuntu 16.04) I've launched

`$node .`

An get the following error

> user@userPC:~/jsconsole$ node .
> /home/user/jsconsole/lib/app.js:44
>   const { id } = req.params;
>             ^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:442:10)
>     at startup (node.js:136:18)
>     at node.js:966:3
>

**Comment by remy** [comment]
You need node 8

**Comment by Kodedyukh** [comment]
Hi,

thanks for reply!

Did you mean?

node *

It gives me the following error:

user@userPC:~/jsconsole$ node *
module.js:328
    throw err;
    ^

Error: Cannot find module './sse'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/jsconsole/lib/index.js:3:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

Thank you in advance!

**Comment by remy** [comment]
No, you need to use node version 8 to run the new codebase

**Comment by Kodedyukh** [comment]
I've tried but get the following

user@userPC:~/jsconsole$ node 8
module.js:328
    throw err;
    ^

Error: Cannot find module '/home/user/jsconsole/8'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by remy** [comment]
Can I politely suggest that if you're unsure how to run node then you're
better off using the live version?

Head over to nodejs.org for more info on node, but you're running node the
executable against a non existent file called "8".

See node docs on how to check your version, and the URL above includes all
that info.

**Comment by Kodedyukh** [comment]
Thank you! 

That's all right. I'll check the docs.

Please consider updating the readme file, it seems like following instructions given there may be not that straightforward for a noob like me)
