### ISSUE TITLE
No actions after :listen in 2.0.0 beta 14

### ISSUE THREAD

**Issue by Liovareg** [remy/jsconsole#104]
### Context 
I'm trying to make jsconsole hosted on jsconsole.com to listen 

### Actual 
nothing happens.

Console output:
![image](https://user-images.githubusercontent.com/11192909/31190056-a5a4c034-a942-11e7-8d58-fa3c39488821.png)

```
internal-commands.js:109 GET https://jsconsole.com/remote/aaa 404 ()
(anonymous) @ internal-commands.js:109
n @ runtime.js:65
(anonymous) @ runtime.js:303
e.(anonymous function) @ runtime.js:117
n @ main.00878696.js:6266
(anonymous) @ main.00878696.js:6266
(anonymous) @ main.00878696.js:6266
(anonymous) @ internal-commands.js:107
(anonymous) @ App.js:56
n @ runtime.js:65
(anonymous) @ runtime.js:303
e.(anonymous function) @ runtime.js:117
n @ main.00878696.js:6108
(anonymous) @ main.00878696.js:6108
(anonymous) @ main.00878696.js:6108
e @ main.00878696.js:6109
(anonymous) @ Input.js:88
n @ runtime.js:65
(anonymous) @ runtime.js:303
e.(anonymous function) @ runtime.js:117
n @ main.00878696.js:6136
(anonymous) @ main.00878696.js:6136
(anonymous) @ main.00878696.js:6136
e @ main.00878696.js:6142
m @ preact.esm.js:266
internal-commands.js:110 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at https://jsconsole.com/static/js/main.00878696.js:1:141362
    at n (https://jsconsole.com/static/js/main.00878696.js:1:383859)
    at Generator._invoke (https://jsconsole.com/static/js/main.00878696.js:1:384981)
    at Generator.e.(anonymous function) [as next] (https://jsconsole.com/static/js/main.00878696.js:1:384038)
    at n (https://jsconsole.com/static/js/main.00878696.js:1:137422)
    at https://jsconsole.com/static/js/main.00878696.js:1:137516
    at <anonymous>
(anonymous) @ internal-commands.js:110
n @ runtime.js:65
(anonymous) @ runtime.js:303
e.(anonymous function) @ runtime.js:117
n @ main.00878696.js:6266
(anonymous) @ main.00878696.js:6266
Promise rejected (async)
n @ main.00878696.js:6136
(anonymous) @ main.00878696.js:6136
(anonymous) @ main.00878696.js:6136
e @ main.00878696.js:6142
m @ preact.esm.js:266
```

### Expected
jsconsole to start new session

**Comment by nbouhid** [comment]
+1

**Comment by remy** [comment]
Depreciated. Use 1.jsconsole.com but it will eventually shutdown. Unless I put some kind of payment process in place to support the ongoing costs of jsconsole.
