### ISSUE TITLE
BigInt literal throws error or not yet supported?

### ISSUE THREAD

**Issue by pvzzombs** [remy/jsconsole#152]
Type `1n` and press Enter.
An error will be thrown:
``{
  "stack": "SyntaxError: Identifier directly after number (1:15)\n    at e.G.raise (https://jsconsole.com/static/js/main.d3742b71.js:1:275830)\n    at e.t.readNumber (https://jsconsole.com/static/js/main.d3742b71.js:1:222008)\n    at e.t.getTokenFromCode (https://jsconsole.com/static/js/main.d3742b71.js:1:219711)\n    at e.t.readToken (https://jsconsole.com/static/js/main.d3742b71.js:1:214074)\n    at e.t.nextToken (https://jsconsole.com/static/js/main.d3742b71.js:1:213962)\n    at e.t.next (https://jsconsole.com/static/js/main.d3742b71.js:1:212897)\n    at e.t.eat (https://jsconsole.com/static/js/main.d3742b71.js:1:212967)\n    at e.z.expect (https://jsconsole.com/static/js/main.d3742b71.js:1:228979)\n    at e.H.parseBlock (https://jsconsole.com/static/js/main.d3742b71.js:1:237755)\n    at et.parseFunctionBody (https://jsconsole.com/static/js/main.d3742b71.js:1:272781)",
  "message": "Identifier directly after number (1:15)",
  "pos": 15,
  "loc": {
    "line": 1,
    "column": 15
  }
}``
which says: 
`"Identifier directly after number"`

It looks like <b>BigInt</b> literals don't yet work or maybe the parser doesn't yet implented parsing <b>BigInt</b> literals. But I tried to type window and I saw the `BigInt Object`.

**Comment by rsodre** [comment]
I need this all the time!
Should be something really simple like change the module target version
